name: Upload Azure Storage

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name tatsukonitestv2b643 \
              --auth-mode key \
              --destination upload-test \
              --source ./src \
              --overwrite

      - name: Logout
        run: |
          az logout
        if: always()
